Repository AlfiyaSiddique/TastyTrails, pull requests merged in 2024-10, with the labels that each got.

#7 Display Password Requirments
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level1

#25 Add Automated Greeting Workflow
  .github/workflows/greetings.yml
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#30 added instructions to setup the project locally
  CONTRIBUTING.md
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#34 CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#27 Notification bell Added
  frontend/src/Components/Navbar.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#36 Applied pagination in both frontend and backend
  backend/Controllers/RecipeController.js
  frontend/src/Components/Pagination.jsx
  frontend/src/Pages/Landing.jsx
  frontend/src/Pages/Recipes.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#42 Bug fix added validation Issue #31
  backend/Controllers/UserController.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/AddRecipe.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#66 Make Navbar Sticky #12
  frontend/src/Components/Navbar.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#74 Update README.md
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#51 Frontend loading skeleton integrated, with necessary changes
  frontend/src/Pages/Dashboard.jsx
  frontend/src/Pages/Landing.jsx
  frontend/src/Pages/Recipes.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#92 Feature improvement/using backendUrl through env for best practice
  backend/package-lock.json
  backend/server.js
  frontend/.env
  frontend/.gitignore
  frontend/common/backendUrl.js
  frontend/src/Components/Navbar.jsx
  frontend/src/Pages/AddRecipe.jsx
  frontend/src/Pages/Dashboard.jsx
  frontend/src/Pages/Landing.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/Recipes.jsx
  frontend/src/Pages/Signup.jsx
  frontend/src/Pages/UpdateRecipe.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#63 Fixed #13 : Scroll to top Component
  frontend/src/App.jsx
  frontend/src/Components/Scrolltotop.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#97 Fixed #50 :Auto-Label Issues and Pull Requests on Creation
  .github/workflows/auto-label.yml
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#101 Additon of All Contributors | Issue #93
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#65 Added issues_templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-feature.yml
  .github/ISSUE_TEMPLATE/styling.yml
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#81 feat: rateLimit Implementation
  backend/middleware/rateLimit.js
  backend/server.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#64 Fixes issue #9: <fixed signup page>
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#108 Bug fix recipie deletions issue #43
  frontend/src/Pages/AddRecipe.jsx
  frontend/src/Pages/Dashboard.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#83 added rate-us/contact-us form
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#109 Bug fix GitHub images issue #44
  backend/.env
  backend/Controllers/RecipeController.js
  backend/package-lock.json
  backend/package.json
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#131 Bug fix sign up issue #128
  backend/Controllers/RecipeController.js
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#130 Bug fix issues template #103
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/new-feature.yml
  .github/ISSUE_TEMPLATE/styling.yml
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#142 Issue #96 Add Responsive Navbar with Menubar
  frontend/src/Components/Navbar.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#133 added validations#120
  frontend/common/validation.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#129 resolved the reference error for pagination issue #102
  frontend/src/Pages/Recipes.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#145 Grafana and Prometheus Integration in Backend
  backend/.env.example
  backend/.gitignore
  backend/README.md
  backend/docker-compose.yml
  backend/package-lock.json
  backend/package.json
  backend/prometheus-config.example.yml
  backend/server.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#148 Bug footer
  frontend/index.html
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#149 Update Landing.jsx
  frontend/src/Pages/Landing.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#151 scroll bar added : Scroll bar added
  frontend/src/App.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#162 Update README.md
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#175 feature nd landing section extra spaces
  frontend/src/Pages/Landing.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#185 Bug URL mismatch and made the footer change
  frontend/.env
  frontend/src/Components/Footer.jsx
  frontend/src/Pages/Recipes.jsx
  frontend/src/Pages/Signup.jsx
  frontend/src/Pages/UpdateRecipe.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#187 Auto redirect to user profile Issue #124
  frontend/src/Pages/Landing.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#164 Feature google auth
  backend/package-lock.json
  backend/package.json
  frontend/.env
  frontend/common/useGoogleAuth.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/Signup.jsx
  frontend/src/main.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#165 Feature pwa app
  backend/.env.example
  backend/Controllers/RecipeController.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/540x720.png
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/vite.config.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#181 Feature/feedback : #167 done
  backend/.env.example
  backend/Controllers/UserController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/web.js
  backend/server.js
  frontend/src/App.css
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#201 [feat] : Added Multi-Lingual support to TastyTrails
  frontend/src/Components/Footer.jsx
  frontend/src/Components/GoogleTranslate.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#221 Added Comment section
  .gitignore
  backend/Controllers/RecipeController.js
  backend/models/Comment.js
  backend/models/Recipe.js
  backend/routes/web.js
  frontend/common/useGoogleAuth.js
  frontend/src/Components/Cards.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/OneRecipe.jsx
  frontend/src/Pages/Signup.jsx
  package-lock.json
  package.json
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#229 Fix footer overflow on larger screens and adjust text and icon sizes …
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/src/App.css
  frontend/src/Components/Footer.jsx
  frontend/src/Components/GoogleTranslate.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#252 Updated navbar
  frontend/src/Components/Navbar.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#255 Update README.md
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#231 Set the limit in text line Cards.jsx
  frontend/src/App.css
  frontend/src/Components/Cards.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#254 Fixes #188 Add debouncing while searching
  frontend/src/Pages/Recipes.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#246 Enhanced the scroll behavior which was caused by footer
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#260 Fix Comment Section Not Displaying After Refresh
  .gitignore
  backend/Controllers/RecipeController.js
  backend/server.js
  frontend/.env
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#262 Added Color to Navbar and Justified Texts
  frontend/src/App.css
  frontend/src/Components/Navbar.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#259 🛠️FiX: Feedback form - Name field validation
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#273 Added 404 page
  frontend/src/App.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/NotFound.jsx
  frontend/src/Pages/Signup.jsx
  frontend/src/assets/Images/food404.png
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#274 Feature pr template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-label.yml
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#275 Added security policy
  SECURITY.MD
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#245 Added Privacy-Policy
  frontend/src/App.jsx
  frontend/src/Components/Footer.jsx
  frontend/src/Components/Navbar.jsx
  frontend/src/Components/PrivacyPolicy.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#291 enhance styling of footer and navbar in mobile view
  frontend/src/Components/Footer.jsx
  frontend/src/Components/GoogleTranslate.jsx
  frontend/src/Components/Navbar.jsx
  frontend/src/Components/Scrolltotop.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#311 Enhanced footer with background
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#297 Share recipie option
  backend/Controllers/RecipeController.js
  backend/Controllers/UserController.js
  backend/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Cards.jsx
  frontend/src/Pages/OneRecipe.jsx
  frontend/src/Pages/Recipes.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#329 remove extra semicol from bottom of the footer
  frontend/src/main.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#339 Replaced Required Field Validation from Alert Windows to Toast notification system
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#350 Implemented Character Length Validation on Feedback Message
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#341 Feature like dislike
  .github/workflows/auto-label.yml
  backend/.env.example
  backend/Controllers/RecipeController.js
  backend/models/User.js
  backend/routes/web.js
  backend/server.js
  frontend/src/Components/Cards.jsx
  frontend/src/Components/Footer.jsx
  frontend/src/Pages/Dashboard.jsx
  frontend/src/Pages/Login.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#352 [FEAT] Added Testimonial Component to Landing Page
  frontend/package.json
  frontend/src/Components/Testimonial.jsx
  frontend/src/Pages/Landing.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#343 hovering effect added on recepies
  backend/server.js
  frontend/src/Components/Cards.jsx
  frontend/src/Pages/OneRecipe.jsx
  package-lock.json
  package.json
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#349 Add feedback Implementation
  backend/Controllers/RecipeController.js
  backend/Controllers/UserController.js
  backend/models/Comment.js
  backend/models/feedback.js
  backend/routes/web.js
  backend/server.js
  frontend/src/Pages/OneRecipe.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#344 Feature forgot password
  backend/Controllers/UserController.js
  backend/package-lock.json
  backend/routes/web.js
  frontend/.env
  frontend/src/App.jsx
  frontend/src/Pages/ForgotPassword.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/ResetPassword.jsx
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#313 Feat: added auto-labelling PR's
  .github/workflows/auto-label.yml
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#375 Add GIF Animation as Title Header [Fixed @362]
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#228 Github Workflow : Notify Contributors When Pull Requests Are Merged
  .github/workflows/auto-comment-on-pr.yml
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#386 [bug] Fixed github workflow - auto comment on PR
  .github/workflows/auto-comment-on-pr.yml
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#387 Add GIF Animation as Title Header Visible [Fixed #383]
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#388 Fixed like button click on recipe card
  frontend/.env
  frontend/src/Components/Cards.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#391 Added patch route in backend to fix share recipe count
  backend/Controllers/RecipeController.js
  backend/routes/web.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#392 Fix comment fetching in frontend
  frontend/src/Pages/OneRecipe.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#394 ADD seed data
  CONTRIBUTING.md
  backend/package-lock.json
  backend/package.json
  backend/seed.js
  frontend/src/Pages/Recipes.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#397 Loader at entry
  backend/server.js
  frontend/src/Components/Loader.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#382 Profile Picture Functionality
  backend/.env.example
  backend/Controllers/UserController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/web.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Dashboard.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#377 Updated footer
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#307 Updated ui of Login page
  frontend/package-lock.json
  frontend/public/newFoodSignup.jpeg
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#404 Implement Helmet Middleware for Improved Security
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#395 Fix comments
  backend/Controllers/RecipeController.js
  backend/Controllers/UserController.js
  backend/models/Comment.js
  frontend/.env.example
  frontend/src/Pages/OneRecipe.jsx
  frontend/src/Pages/Recipes.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted
