Repository AlfiyaSiddique/TastyTrails, pull requests merged in 2024-11, with the labels that each got.

#408 Integrated Testimonials Carousel with backend and added new APIs with redesigned modal
  backend/Controllers/UserController.js
  backend/models/feedback.js
  backend/routes/web.js
  frontend/src/Components/Footer.jsx
  frontend/src/Components/Testimonial.jsx
  frontend/src/Pages/Landing.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#310 Enhance/UI of signup
  frontend/public/registerimage.jpg
  frontend/src/Pages/Login.jsx
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#423 Implement Feature to Delete User Account
  backend/Controllers/UserController.js
  backend/routes/web.js
  frontend/src/Pages/Dashboard.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#429 seo enhancement for your website
  frontend/public/robots.txt
  frontend/public/sitemap.xml
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#431 Create User Profile Page for Viewing Other Users' Recipes and Liked Recipes
  frontend/src/App.jsx
  frontend/src/Components/Testimonial.jsx
  frontend/src/Pages/Profile.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#434 Fixed Recipe Image Storage & "Update Recipe" Page Improvements
  backend/.env.example
  backend/Controllers/RecipeController.js
  backend/models/Recipe.js
  frontend/src/Pages/UpdateRecipe.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#435 Add Email Verification During Sign-Up
  backend/.env.example
  backend/Controllers/UserController.js
  backend/Controllers/VerificationController.js
  backend/Utils/emailUtils.js
  backend/models/User.js
  backend/routes/web.js
  frontend/src/App.jsx
  frontend/src/Pages/EmailVerification.jsx
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#436 Added Resend Email Verification and Delete Unverified Users after 24 Hours
  backend/.env.example
  backend/Controllers/UserController.js
  backend/Controllers/VerificationController.js
  backend/Utils/emailUtils.js
  backend/models/User.js
  backend/package.json
  backend/routes/web.js
  backend/server.js
  frontend/src/App.jsx
  frontend/src/Pages/EmailVerification.jsx
  frontend/src/Pages/ResendVerification.jsx
  frontend/src/Pages/Signup.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#438 Added Follow Feature to User Profile (Backend & Frontend Integration)
  backend/Controllers/UserController.js
  backend/routes/web.js
  frontend/src/Pages/Dashboard.jsx
  frontend/src/Pages/Profile.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#443 issue number #440 is solved
  frontend/package-lock.json
  frontend/src/Components/Footer.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#445 Added User Search Page Feature on Tasty Trails
  backend/Controllers/UserController.js
  backend/routes/web.js
  frontend/src/App.jsx
  frontend/src/Components/Navbar.jsx
  frontend/src/Pages/SearchPage.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#446 Added Follower and Following List to Profile Page
  backend/Controllers/UserController.js
  backend/routes/web.js
  frontend/src/Components/FollowerModal.jsx
  frontend/src/Pages/Profile.jsx
Labels: gssoc-ext, level 3, hacktoberfest-accepted
